Server = input("Enter chopin, bach, or parsons")
# Chopin - 6
# Bach - 4
# Parsons - 7

if (Server=='chopin'):
    print('+--------------------------------------+--------------------------------------+')
    print('|                                      |                                      |')
    print('|  Day 00 Month 00 on Chopin           |  Day 00 Month 00 on Chopin           |')
    print('|                                      |                                      |')
    print('|<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>|<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>|')
    print('|                                      |                                      |')
    print('|  Day 00 Month 00 on Chopin           |  Day 00 Month 00 on Chopin           |')
    print('|                                      |                                      |')
    print('|  Zero Dumps:                         |  Zero Dumps:                         |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('+--------------------------------------+--------------------------------------+')

elif (Server=='bach'):
    print('+--------------------------------------+--------------------------------------+')
    print('|                                      |                                      |')
    print('|  Day 00 Month 00 on Bach             |  Day 00 Month 00 on Bach             |')
    print('|                                      |                                      |')
    print('|<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>|<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>|')
    print('|                                      |                                      |')
    print('|  Day 00 Month 00 on Chopin           |  Day 00 Month 00 on Chopin           |')
    print('|                                      |                                      |')
    print('|  Zero Dumps:                         |  Zero Dumps:                         |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('+--------------------------------------+--------------------------------------+')

elif (Server=='parsons'):
    print('+--------------------------------------+--------------------------------------+')
    print('|                                      |                                      |')
    print('|  Day 00 Month 00 on Parsons          |  Day 00 Month 00 on Parsons          |')
    print('|                                      |                                      |')
    print('|<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>|<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>|')
    print('|                                      |                                      |')
    print('|  Day 00 Month 00 on Chopin           |  Day 00 Month 00 on Chopin           |')
    print('|                                      |                                      |')
    print('|  Zero Dumps:                         |  Zero Dumps:                         |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('|                                      |                                      |')
    print('+--------------------------------------+--------------------------------------+')
else:
    print('ERROR: Invalid Entry')